server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?characterEncoding=UTF-8
    username: test
    password: test
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
security:
  user:
    password: password
    
logging:
  level:
    org.springframework.security: DEBUG